name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    name: Lint, Test, Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: echo "Tests skipped for now"

      - name: Setup JDK for Android
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build Android Release
        working-directory: android
        run: ./gradlew assembleRelease